[tool.poetry]
name = "data-didask"
version = "0.1.0"
description = ""
authors = ["Selim Raboudi <selim.raboudi@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.12"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
